language: java 
jdk: openjdk13
dist: trusty
script:
  # ingest user agent
  - ./gradlew :modules:ingest-user-agent:test --tests org.elasticsearch.ingest.useragent.UserAgentProcessorTests
  # ingest geoip 
  - ./gradlew :modules:ingest-geoip:test --tests org.elasticsearch.ingest.geoip.GeoIpProcessorTests
  # transport netty4
  - ./gradlew :modules:transport-netty4:test --tests org.elasticsearch.http.netty4.Netty4HttpServerTransportTests
  # ingest common
  - ./gradlew :modules:ingest-common:test --tests org.elasticsearch.ingest.common.DateProcessorTests
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.3
